// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/queue/queue.proto

package queue

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求进入令牌
type RequestTokenReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestTokenReq) Reset()         { *m = RequestTokenReq{} }
func (m *RequestTokenReq) String() string { return proto.CompactTextString(m) }
func (*RequestTokenReq) ProtoMessage()    {}
func (*RequestTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f19f82a9e8d3cfaf, []int{0}
}

func (m *RequestTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestTokenReq.Unmarshal(m, b)
}
func (m *RequestTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestTokenReq.Marshal(b, m, deterministic)
}
func (m *RequestTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestTokenReq.Merge(m, src)
}
func (m *RequestTokenReq) XXX_Size() int {
	return xxx_messageInfo_RequestTokenReq.Size(m)
}
func (m *RequestTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_RequestTokenReq proto.InternalMessageInfo

func (m *RequestTokenReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// 返回是否需要排队
type RequestTokenResp struct {
	FrontNumber          int32    `protobuf:"varint,1,opt,name=frontNumber,proto3" json:"frontNumber,omitempty"`
	WaitSeconds          int32    `protobuf:"varint,2,opt,name=waitSeconds,proto3" json:"waitSeconds,omitempty"`
	OldToken             string   `protobuf:"bytes,3,opt,name=oldToken,proto3" json:"oldToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestTokenResp) Reset()         { *m = RequestTokenResp{} }
func (m *RequestTokenResp) String() string { return proto.CompactTextString(m) }
func (*RequestTokenResp) ProtoMessage()    {}
func (*RequestTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f19f82a9e8d3cfaf, []int{1}
}

func (m *RequestTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestTokenResp.Unmarshal(m, b)
}
func (m *RequestTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestTokenResp.Marshal(b, m, deterministic)
}
func (m *RequestTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestTokenResp.Merge(m, src)
}
func (m *RequestTokenResp) XXX_Size() int {
	return xxx_messageInfo_RequestTokenResp.Size(m)
}
func (m *RequestTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_RequestTokenResp proto.InternalMessageInfo

func (m *RequestTokenResp) GetFrontNumber() int32 {
	if m != nil {
		return m.FrontNumber
	}
	return 0
}

func (m *RequestTokenResp) GetWaitSeconds() int32 {
	if m != nil {
		return m.WaitSeconds
	}
	return 0
}

func (m *RequestTokenResp) GetOldToken() string {
	if m != nil {
		return m.OldToken
	}
	return ""
}

// 推送登录令牌
type RequestTokenPush struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestTokenPush) Reset()         { *m = RequestTokenPush{} }
func (m *RequestTokenPush) String() string { return proto.CompactTextString(m) }
func (*RequestTokenPush) ProtoMessage()    {}
func (*RequestTokenPush) Descriptor() ([]byte, []int) {
	return fileDescriptor_f19f82a9e8d3cfaf, []int{2}
}

func (m *RequestTokenPush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestTokenPush.Unmarshal(m, b)
}
func (m *RequestTokenPush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestTokenPush.Marshal(b, m, deterministic)
}
func (m *RequestTokenPush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestTokenPush.Merge(m, src)
}
func (m *RequestTokenPush) XXX_Size() int {
	return xxx_messageInfo_RequestTokenPush.Size(m)
}
func (m *RequestTokenPush) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestTokenPush.DiscardUnknown(m)
}

var xxx_messageInfo_RequestTokenPush proto.InternalMessageInfo

func (m *RequestTokenPush) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestTokenReq)(nil), "queue.RequestTokenReq")
	proto.RegisterType((*RequestTokenResp)(nil), "queue.RequestTokenResp")
	proto.RegisterType((*RequestTokenPush)(nil), "queue.RequestTokenPush")
}

func init() { proto.RegisterFile("api/queue/queue.proto", fileDescriptor_f19f82a9e8d3cfaf) }

var fileDescriptor_f19f82a9e8d3cfaf = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x2c, 0xc8, 0xd4,
	0x2f, 0x2c, 0x4d, 0x2d, 0x4d, 0x85, 0x90, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60,
	0x8e, 0x92, 0x22, 0x17, 0x7f, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x49, 0x48, 0x7e, 0x76, 0x6a,
	0x5e, 0x50, 0x6a, 0xa1, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67,
	0x10, 0x53, 0x66, 0x8a, 0x52, 0x11, 0x97, 0x00, 0xaa, 0x92, 0xe2, 0x02, 0x21, 0x05, 0x2e, 0xee,
	0xb4, 0xa2, 0xfc, 0xbc, 0x12, 0xbf, 0xd2, 0xdc, 0xa4, 0xd4, 0x22, 0xb0, 0x62, 0xd6, 0x20, 0x64,
	0x21, 0x90, 0x8a, 0xf2, 0xc4, 0xcc, 0x92, 0xe0, 0xd4, 0xe4, 0xfc, 0xbc, 0x94, 0x62, 0x09, 0x26,
	0x88, 0x0a, 0x24, 0x21, 0x21, 0x29, 0x2e, 0x8e, 0xfc, 0x9c, 0x14, 0xb0, 0x99, 0x12, 0xcc, 0x60,
	0xdb, 0xe0, 0x7c, 0x25, 0x0d, 0x54, 0x3b, 0x03, 0x4a, 0x8b, 0x33, 0x84, 0x44, 0xb8, 0x58, 0x4b,
	0xc0, 0x8a, 0x21, 0x4e, 0x83, 0x70, 0x92, 0xd8, 0xc0, 0xde, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xd4, 0x6f, 0x25, 0x8c, 0xe7, 0x00, 0x00, 0x00,
}
